// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjb_6F019XCvrQPW7Mh1LuGnL4-o294PE',
    appId: '1:1074059811680:web:ed28ae8a2b34bdd83ddc05',
    messagingSenderId: '1074059811680',
    projectId: 'chat-app-6137e',
    authDomain: 'chat-app-6137e.firebaseapp.com',
    storageBucket: 'chat-app-6137e.appspot.com',
    measurementId: 'G-3PFBLW3XN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyGIM6saYoWm0pR1ULRF9WSyfaHM2PIQk',
    appId: '1:1074059811680:android:46320aa56de7c5773ddc05',
    messagingSenderId: '1074059811680',
    projectId: 'chat-app-6137e',
    storageBucket: 'chat-app-6137e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Yos1kQcmJ41OTWsay2PDtnUMfScQ4hA',
    appId: '1:1074059811680:ios:d2607c07c3cb02b13ddc05',
    messagingSenderId: '1074059811680',
    projectId: 'chat-app-6137e',
    storageBucket: 'chat-app-6137e.appspot.com',
    iosClientId: '1074059811680-8bm7lkaggpfolvv6iaptv3gilafmatvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
